# Generated by Django 6.0.3 on 2026-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log_type', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
